### ISSUE TITLE
Incompatible Versions code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'

### ISSUE THREAD

**Issue by gkankanh** [jhipster/generator-jhipster-svelte#1030]
Node v17.6.0

jhipster 7.7.0Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './cli/utils' is not defined by "exports" in /usr/local/lib/node_modules/generator-jhipster-svelte/node_modules/generator-jhipster/package.json
    at new NodeError (node:internal/errors:372:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:433:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:712:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster-svelte/cli/shipster.js:4:20) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'

**Comment by vishal423** [comment]
Jhipster v`7.5.x` is the current supported version. I suggest to use `shipster` cli as that internally uses the compatible JHipster version.

**Comment by gkankanh** [comment]
Hi Vishal
Downgrading jhipster to 7.5.0 still causes the same issue. I am on M1 Mac if that helps!.[gopal] ~/projects/sv > jhipster --version
INFO! Using JHipster version installed globally
7.5.0
[gopal] ~/projects/sv > shipster --version
node:internal/modules/cjs/loader:488
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './cli/utils' is not defined by "exports" in /usr/local/lib/node_modules/generator-jhipster-svelte/node_modules/generator-jhipster/package.json
    at new NodeError (node:internal/errors:372:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:433:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:712:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster-svelte/cli/shipster.js:4:20) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v17.6.0
