### ISSUE TITLE
Generation fails with error: "Error: No parser could be inferred for file"

### ISSUE THREAD

**Issue by Cyneath** [jhipster/generator-jhipster-svelte#1371]
Just updated [generator-jhipster-svelte](https://github.com/jhipster/generator-jhipster-svelte) to 0.10.0 using `npm update -g generator-jhipster-svelte`.

Then I generated a new app using mostly default options. During the generation the following error is thrown:
```
× An error occured while running jhipster:bootstrap#commitFiles
ERROR! Error parsing file src\main\webapp\app\routes\+error.svelte: Error: No parser could be inferred for file: src\main\webapp\app\routes\+error.svelte

At: 1: <script>
2:      export let status
3:      export let error
4: </script>
5:
6: <svelte:head>
7:      <title>{status}</title>
8: </svelte:head>
9: <h1>{status}</h1>
10:
11: <p>{error}</p>
12:
Error: Error parsing file src\main\webapp\app\routes\+error.svelte: Error: No parser could be inferred for file: src\main\webapp\app\routes\+error.svelte

At: 1: <script>
2:      export let status
3:      export let error
4: </script>
5:
6: <svelte:head>
7:      <title>{status}</title>
8: </svelte:head>
9: <h1>{status}</h1>
10:
11: <p>{error}</p>
12:
    at patternSpy.dot (C:\Users\Kenneth\AppData\Roaming\npm\node_modules\generator-jhipster-svelte\node_modules\generator-jhipster\generators\generator-transforms.js:79:15)
    at async PTransform.transform [as _transform] (C:\Users\Kenneth\AppData\Roaming\npm\node_modules\generator-jhipster-svelte\node_modules\p-transform\index.js:127:7)
    at async PTransform.queuedTransform (C:\Users\Kenneth\AppData\Roaming\npm\node_modules\generator-jhipster-svelte\node_modules\p-transform\index.js:88:26)
    at async run (C:\Users\Kenneth\AppData\Roaming\npm\node_modules\generator-jhipster-svelte\node_modules\p-queue\dist\index.js:163:29)
```

The webapp folder in src/main is completely missing after generation.

![image](https://user-images.githubusercontent.com/53078027/189503660-f352c414-0425-4a2f-ba81-6c573b263e89.png)

OS: Windows 10
Node: v16.16.0
NPM: 8.19.1
Svelte Hipster: v0.10.0

Complete Log:
```
INFO! Using JHipster version installed globally
INFO! No custom sharedOptions found within blueprint: generator-jhipster-svelte at C:/Users/Kenneth/AppData/Roaming/npm/node_modules/generator-jhipster-svelte
INFO! No custom commands found within blueprint: generator-jhipster-svelte at C:/Users/Kenneth/AppData/Roaming/npm/node_modules/generator-jhipster-svelte
(node:16472) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./cli/" in the "exports" field module resolution of the package at C:\Users\Kenneth\AppData\Roaming\npm\node_modules\generator-jhipster-svelte\node_modules\generator-jhipster\package.json.
Update this package.json to use a subpath pattern like "./cli/*".
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:16472) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./lib/util/" in the "exports" field module resolution of the package at C:\Users\Kenneth\AppData\Roaming\npm\node_modules\generator-jhipster-svelte\node_modules\yeoman-environment\package.json.
Update this package.json to use a subpath pattern like "./lib/util/*".

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
                            https://www.jhipster.tech
Welcome to JHipster v7.9.3

     info Using blueprint generator-jhipster-svelte for app subgenerator
(node:16472) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./generators/" in the "exports" field module resolution of the package at C:\Users\Kenneth\AppData\Roaming\npm\node_modules\generator-jhipster-svelte\node_modules\generator-jhipster\package.json.
Update this package.json to use a subpath pattern like "./generators/*".


    ██████╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
   ██╔════╝ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
   ╚█████╗  ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
    ╚═══██╗ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
   ██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://www.jhipster.tech

Welcome to Svelte Hipster v0.10.0
Application files will be generated in folder: C:\Users\Kenneth\Desktop\svelte\svelte-hipster-0.10.0
 _______________________________________________________________________________________________________________

  If you find Svelte Hipster useful, support with a star and follow https://github.com/jhipster/generator-jhipster-svelte
 _______________________________________________________________________________________________________________

? Which *type* of application would you like to create? Monolithic application (recommended for simple projects)
? What is the base name of your application? jhipster
     info Using blueprint generator-jhipster-svelte for common subgenerator
     info Using blueprint generator-jhipster-svelte for server subgenerator
     info Using blueprint generator-jhipster-svelte for client subgenerator
     info Using blueprint generator-jhipster-svelte for languages subgenerator
? Do you want to make it reactive with Spring WebFlux? No
? What is your default Java package name? com.mycompany.myapp
? Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? Which *type* of database would you like to use? SQL (H2, PostgreSQL, MySQL, MariaDB, Oracle, MSSQL)
? Which *production* database would you like to use? PostgreSQL
? Which *development* database would you like to use? PostgreSQL
? Which cache do you want to use? (Spring cache abstraction) Caffeine (local cache, for a single node)
? Do you want to use Hibernate 2nd level cache? Yes
? Would you like to use Maven or Gradle for building the backend? Maven
? Do you want to use the JHipster Registry to configure, monitor and scale your application? No
? Which other technologies would you like to use?
? Besides Junit, which testing frameworks would you like to use?
? Would you like to install other generators from the JHipster Marketplace? No
Generieren von Schl�sselpaar (Typ RSA, 2.048 Bit) und selbst signiertem Zertifikat (SHA256withRSA) mit einer G�ltigkeit von 99.999 Tagen
        f�r: CN=Java Hipster, OU=Development, O=com.mycompany.myapp, L=, ST=, C=

KeyStore 'C:\Users\Kenneth\Desktop\svelte\svelte-hipster-0.10.0\src\main\resources\config\tls\/keystore.p12' generated successfully.

   create .prettierrc
   create .prettierignore
    force .yo-rc.json
   create package.json
   create .gitattributes
   create .husky\pre-commit
   create .editorconfig
   create .gitignore
   create README.md
   create sonar-project.properties
   create mvnw
   create mvnw.cmd
   create .mvn\jvm.config
   create .mvn\wrapper\maven-wrapper.jar
   create .mvn\wrapper\maven-wrapper.properties
   create npmw
   create npmw.cmd
   create src\main\resources\banner.txt
   create src\main\resources\config\liquibase\changelog\00000000000000_initial_schema.xml
   create src\main\resources\config\liquibase\master.xml
   create src\main\docker\jib\entrypoint.sh
   create checkstyle.xml
   create .devcontainer\Dockerfile
   create pom.xml
   create src\main\resources\logback-spring.xml
   create src\main\resources\i18n\messages.properties
   create .devcontainer\devcontainer.json
   create src\main\docker\app.yml
   create src\main\docker\central-server-config\README.md
   create src\main\docker\jhipster-control-center.yml
   create src\main\docker\zipkin.yml
   create src\main\resources\templates\error.html
   create src\main\docker\sonar.yml
   create src\main\docker\monitoring.yml
   create src\main\docker\prometheus\prometheus.yml
   create src\main\docker\grafana\provisioning\dashboards\dashboard.yml
   create src\main\resources\config\application.yml
   create src\main\docker\grafana\provisioning\dashboards\JVM.json
   create src\main\resources\config\application-dev.yml
   create src\main\docker\grafana\provisioning\datasources\datasource.yml
   create src\main\resources\config\application-tls.yml
   create src\main\resources\config\application-prod.yml
   create src\main\resources\config\bootstrap.yml
   create src\main\resources\config\bootstrap-prod.yml
   create src\main\java\com\mycompany\myapp\security\SpringSecurityAuditorAware.java
   create src\main\java\com\mycompany\myapp\security\UserNotActivatedException.java
   create src\main\java\com\mycompany\myapp\GeneratedByJHipster.java
   create src\main\java\com\mycompany\myapp\config\StaticResourcesWebConfiguration.java
   create src\main\java\com\mycompany\myapp\service\package-info.java
   create src\main\java\com\mycompany\myapp\web\rest\vm\LoginVM.java
   create src\main\java\com\mycompany\myapp\aop\logging\LoggingAspect.java
   create src\main\java\com\mycompany\myapp\config\Constants.java
   create src\main\java\com\mycompany\myapp\web\rest\errors\package-info.java
   create src\main\java\com\mycompany\myapp\security\SecurityUtils.java
   create src\main\java\com\mycompany\myapp\security\AuthoritiesConstants.java
   create src\main\java\com\mycompany\myapp\web\rest\UserJWTController.java
   create src\main\java\com\mycompany\myapp\config\package-info.java
   create src\main\java\com\mycompany\myapp\config\LocaleConfiguration.java
   create src\main\java\com\mycompany\myapp\web\rest\errors\BadRequestAlertException.java
   create src\main\java\com\mycompany\myapp\security\package-info.java
   create src\main\java\com\mycompany\myapp\config\AsyncConfiguration.java
   create src\main\java\com\mycompany\myapp\config\CacheConfiguration.java
   create src\main\java\com\mycompany\myapp\web\rest\errors\ErrorConstants.java
   create src\main\java\com\mycompany\myapp\config\CRLFLogConverter.java
   create src\main\java\com\mycompany\myapp\config\DatabaseConfiguration.java
   create src\main\java\com\mycompany\myapp\web\rest\errors\ExceptionTranslator.java
   create src\main\java\com\mycompany\myapp\security\jwt\TokenProvider.java
   create src\main\java\com\mycompany\myapp\JhipsterApp.java
   create src\main\java\com\mycompany\myapp\config\DateTimeFormatConfiguration.java
   create src\main\java\com\mycompany\myapp\domain\package-info.java
   create src\main\java\com\mycompany\myapp\web\rest\errors\FieldErrorVM.java
   create src\test\resources\logback.xml
   create src\main\java\com\mycompany\myapp\security\jwt\JWTFilter.java
   create src\main\java\com\mycompany\myapp\ApplicationWebXml.java
   create src\main\java\com\mycompany\myapp\config\LoggingConfiguration.java
   create src\main\java\com\mycompany\myapp\domain\AbstractAuditingEntity.java
   create src\main\java\com\mycompany\myapp\web\rest\errors\EmailAlreadyUsedException.java
   create src\test\resources\junit-platform.properties
   create src\main\java\com\mycompany\myapp\management\SecurityMetersService.java
   create src\main\java\com\mycompany\myapp\config\ApplicationProperties.java
   create src\main\java\com\mycompany\myapp\repository\package-info.java
   create src\main\java\com\mycompany\myapp\web\rest\errors\InvalidPasswordException.java
   create src\main\java\com\mycompany\myapp\security\jwt\JWTConfigurer.java
   create src\main\java\com\mycompany\myapp\config\JacksonConfiguration.java
   create src\main\java\com\mycompany\myapp\service\EmailAlreadyUsedException.java
   create src\main\java\com\mycompany\myapp\web\rest\errors\LoginAlreadyUsedException.java
   create src\main\java\com\mycompany\myapp\config\SecurityConfiguration.java
   create src\main\java\com\mycompany\myapp\config\LoggingAspectConfiguration.java
   create src\main\java\com\mycompany\myapp\service\InvalidPasswordException.java
   create src\main\java\com\mycompany\myapp\web\rest\vm\package-info.java
   create src\main\java\com\mycompany\myapp\security\DomainUserDetailsService.java
   create src\main\java\com\mycompany\myapp\config\WebConfigurer.java
   create src\main\java\com\mycompany\myapp\service\UsernameAlreadyUsedException.java
   create src\main\java\com\mycompany\myapp\web\rest\package-info.java
   create src\main\java\com\mycompany\myapp\web\rest\ClientForwardController.java
   create src\main\java\com\mycompany\myapp\domain\User.java
   create src\main\java\com\mycompany\myapp\domain\Authority.java
   create src\test\java\com\mycompany\myapp\security\SecurityUtilsUnitTest.java
   create src\main\java\com\mycompany\myapp\repository\AuthorityRepository.java
   create src\main\resources\config\liquibase\data\user.csv
   create src\main\resources\config\liquibase\data\authority.csv
   create src\main\resources\config\liquibase\data\user_authority.csv
   create src\test\java\com\mycompany\myapp\TechnicalStructureTest.java
   create src\test\java\com\mycompany\myapp\config\AsyncSyncConfiguration.java
   create src\test\java\com\mycompany\myapp\config\WebConfigurerTest.java
   create src\test\java\com\mycompany\myapp\IntegrationTest.java
   create src\test\java\com\mycompany\myapp\config\WebConfigurerTestController.java
   create src\test\java\com\mycompany\myapp\config\SpringBootTestClassOrderer.java
   create src\test\java\com\mycompany\myapp\config\StaticResourcesWebConfigurerTest.java
   create src\test\java\com\mycompany\myapp\web\rest\TestUtil.java
   create src\test\java\com\mycompany\myapp\security\DomainUserDetailsServiceIT.java
   create src\test\java\com\mycompany\myapp\web\rest\errors\ExceptionTranslatorTestController.java
   create src\test\java\com\mycompany\myapp\web\rest\errors\ExceptionTranslatorIT.java
   create src\main\java\com\mycompany\myapp\repository\UserRepository.java
   create src\test\java\com\mycompany\myapp\web\rest\ClientForwardControllerTest.java
   create src\main\java\com\mycompany\myapp\service\UserService.java
   create src\test\resources\config\application.yml
   create src\main\java\com\mycompany\myapp\service\MailService.java
   create src\main\resources\templates\mail\activationEmail.html
   create src\main\resources\templates\mail\creationEmail.html
   create src\main\resources\templates\mail\passwordResetEmail.html
   create src\main\java\com\mycompany\myapp\web\rest\vm\ManagedUserVM.java
   create src\test\resources\config\bootstrap.yml
   create src\main\java\com\mycompany\myapp\web\rest\AccountResource.java
   create src\main\java\com\mycompany\myapp\web\rest\UserResource.java
   create src\main\java\com\mycompany\myapp\web\rest\PublicUserResource.java
   create src\main\java\com\mycompany\myapp\web\rest\vm\KeyAndPasswordVM.java
   create src\main\java\com\mycompany\myapp\service\dto\package-info.java
   create src\test\resources\testcontainers.properties
   create src\main\java\com\mycompany\myapp\service\dto\AdminUserDTO.java
   create src\test\resources\META-INF\spring.factories
   create src\main\java\com\mycompany\myapp\service\dto\UserDTO.java
   create src\main\java\com\mycompany\myapp\service\dto\PasswordChangeDTO.java
   create src\test\java\com\mycompany\myapp\config\TestContainersSpringContextCustomizerFactory.java
   create src\test\resources\templates\mail\activationEmail.html
   create src\test\resources\templates\mail\creationEmail.html
   create src\test\resources\templates\mail\passwordResetEmail.html
   create src\test\java\com\mycompany\myapp\web\rest\UserJWTControllerIT.java
   create src\main\java\com\mycompany\myapp\service\mapper\package-info.java
   create src\test\resources\templates\mail\testEmail.html
   create src\test\resources\i18n\messages_en.properties
   create src\main\java\com\mycompany\myapp\service\mapper\UserMapper.java
   create src\test\java\com\mycompany\myapp\management\SecurityMetersServiceTests.java
   create src\test\java\com\mycompany\myapp\security\jwt\TokenProviderTest.java
   create src\test\java\com\mycompany\myapp\web\rest\PublicUserResourceIT.java
   create src\test\java\com\mycompany\myapp\security\jwt\TokenProviderSecurityMetersTests.java
   create src\test\java\com\mycompany\myapp\web\rest\UserResourceIT.java
   create src\test\java\com\mycompany\myapp\security\jwt\JWTFilterTest.java
   create src\test\java\com\mycompany\myapp\web\rest\AccountResourceIT.java
   create src\test\java\com\mycompany\myapp\web\rest\WithUnauthenticatedMockUser.java
   create src\main\java\com\mycompany\myapp\config\LiquibaseConfiguration.java
   create src\test\java\com\mycompany\myapp\service\MailServiceIT.java
   create src\test\java\com\mycompany\myapp\config\EmbeddedSQL.java
   create src\test\java\com\mycompany\myapp\service\UserServiceIT.java
   create src\test\java\com\mycompany\myapp\config\SqlTestContainer.java
   create src\test\java\com\mycompany\myapp\service\mapper\UserMapperTest.java
   create src\test\resources\config\application-testdev.yml
   create src\test\resources\config\application-testprod.yml
   create src\main\docker\postgresql.yml
   create src\test\java\com\mycompany\myapp\config\PostgreSqlTestContainer.java
   create cypress\fixtures\integration-test.png
   create src\test\java\com\mycompany\myapp\config\timezone\HibernateTimeZoneIT.java
   create src\main\webapp\static\img\hipster-192.png
   create src\main\webapp\static\img\hipster-512.png
   create src\main\webapp\static\favicon.ico
   create src\main\webapp\app\lib\svg\app-avatar.svg
   create src\test\java\com\mycompany\myapp\repository\timezone\DateTimeWrapper.java
   create src\test\java\com\mycompany\myapp\repository\timezone\DateTimeWrapperRepository.java
   create src\main\webapp\app\lib\svg\app-logo.svg
   create src\main\webapp\static\img\logo-jhipster.png
   create .eslintignore
   create .eslintrc.json
   create cypress.config.cjs
   create jest.config.cjs
   create jsconfig.json
   create postcss.config.cjs
× An error occured while running jhipster:bootstrap#commitFiles
ERROR! Error parsing file src\main\webapp\app\routes\+error.svelte: Error: No parser could be inferred for file: src\main\webapp\app\routes\+error.svelte

At: 1: <script>
2:      export let status
3:      export let error
4: </script>
5:
6: <svelte:head>
7:      <title>{status}</title>
8: </svelte:head>
9: <h1>{status}</h1>
10:
11: <p>{error}</p>
12:
Error: Error parsing file src\main\webapp\app\routes\+error.svelte: Error: No parser could be inferred for file: src\main\webapp\app\routes\+error.svelte

At: 1: <script>
2:      export let status
3:      export let error
4: </script>
5:
6: <svelte:head>
7:      <title>{status}</title>
8: </svelte:head>
9: <h1>{status}</h1>
10:
11: <p>{error}</p>
12:
    at patternSpy.dot (C:\Users\Kenneth\AppData\Roaming\npm\node_modules\generator-jhipster-svelte\node_modules\generator-jhipster\generators\generator-transforms.js:79:15)
    at async PTransform.transform [as _transform] (C:\Users\Kenneth\AppData\Roaming\npm\node_modules\generator-jhipster-svelte\node_modules\p-transform\index.js:127:7)
    at async PTransform.queuedTransform (C:\Users\Kenneth\AppData\Roaming\npm\node_modules\generator-jhipster-svelte\node_modules\p-transform\index.js:88:26)
    at async run (C:\Users\Kenneth\AppData\Roaming\npm\node_modules\generator-jhipster-svelte\node_modules\p-queue\dist\index.js:163:29)
   create svelte.config.js
   create tailwind.config.cjs

```

**Comment by vishal423** [comment]
Thanks for the detailed issue description. I confirm the issue. It stems from the wrong categorization of dependencies. I will soon do a new patch release to fix this issue.
