### ISSUE TITLE
No parser could be inferred

### ISSUE THREAD

**Issue by TorzsaCristian** [jhipster/generator-jhipster-svelte#1805]
Hello. I've just created an app
Jhipster@7.9.3
jsvelte@v1.0.0

✖ An error occured while running jhipster:bootstrap#commitFiles
Error running generator entities: Error: Error parsing file src/main/webapp/app/lib/entities/entity-menu.svelte: Error: No parser could be inferred for file: src/main/webapp/app/lib/entities/entity-menu.svelte

 at patternSpy.dot (/jhipster-sample-app-svelte-main/node_modules/generator-jhipster/generators/generator-transforms.js:79:15)
    at async PTransform.transform [as _transform] (/jhipster-sample-app-svelte-main/node_modules/p-transform/index.js:127:7)
    at async PTransform.queuedTransform (/jhipster-sample-app-svelte-main/node_modules/p-transform/index.js:88:26)
    at async run (/jhipster-sample-app-svelte-main/node_modules/p-queue/dist/index.js:163:29)

**Comment by vishal423** [comment]
It seems like a version mismatch issue. Could you share the command you tried?

**Comment by TorzsaCristian** [comment]
jsvelte import-jdl my-jdl.jdl. 
It created all my backend services and files, but when trying to create the frontend, it crashed at this first menu.

**Comment by vishal423** [comment]
Thanks for the info. I will try to take a look over weekend

**Comment by vishal423** [comment]
I tried reproducing the issue with sample `app.jdl` shared on the `README` document and everything seems to be running fine. Could you try to reinstall Svelte blueprint and try again? If issue persists, please share the following details:
- `my-jdl.jdl` file
-  nodeJS version
-  OS details

**Comment by vishal423** [comment]
Closing due to lack of response. The issue is not reproducible and requires more details for reproduction/debugging.
