### ISSUE TITLE
Support release of JHipster `v8.7` release

### ISSUE THREAD

**Issue by vishal423** [jhipster/generator-jhipster-svelte#2075]
JHipster `v8.3` seems contain few breaking changes related to the `server` sub-generator. CI shows, below stack trace during application generation:

```
ERROR! An error occured while running jhipster-svelte:server#parseCommand
ERROR! ERROR! Command not found for generator jhipster-svelte:server
Error: Command not found for generator jhipster-svelte:server
    at default.getCurrentJHipsterCommand (file:///home/runner/work/generator-jhipster-svelte/generator-jhipster-svelte/node_modules/generator-jhipster/dist/generators/base-core/generator.js:228:23)
    at async default.parseCurrentJHipsterCommand (file:///home/runner/work/generator-jhipster-svelte/generator-jhipster-svelte/node_modules/generator-jhipster/dist/generators/base-core/generator.js:240:34)
    at async default.parseCommand (file:///home/runner/work/generator-jhipster-svelte/generator-jhipster-svelte/node_modules/generator-jhipster/dist/generators/server/generator.js:71:17)
    at async default.executeTask (file:///home/runner/work/generator-jhipster-svelte/generator-jhipster-svelte/node_modules/yeoman-generator/dist/actions/lifecycle.js:244:13)
    at async runLoop.add.once (file:///home/runner/work/generator-jhipster-svelte/generator-jhipster-svelte/node_modules/yeoman-environment/dist/environment-base.js:395:17)
```

**Comment by vishal423** [comment]
@mraible , @pascalgrimaud , Can we add some bounty to this issue?

**Comment by pascalgrimaud** [comment]
Done :-)
